// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ukw_Z4ZiLpk4lT73PsZ6lQAz788HnWw',
    appId: '1:388128570387:web:890f68e0d5d35ea01353e6',
    messagingSenderId: '388128570387',
    projectId: 'postify-app-project',
    authDomain: 'postify-app-project.firebaseapp.com',
    storageBucket: 'postify-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6gRNYoS1SwC1P38AqPWukXJ_HcEXH5s',
    appId: '1:388128570387:android:d90148aa20dde3021353e6',
    messagingSenderId: '388128570387',
    projectId: 'postify-app-project',
    storageBucket: 'postify-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1uf7PZj0PC_hrLUsILPBaxNNrJUJmEfI',
    appId: '1:388128570387:ios:0142a8de056715e31353e6',
    messagingSenderId: '388128570387',
    projectId: 'postify-app-project',
    storageBucket: 'postify-app-project.firebasestorage.app',
    iosBundleId: 'com.example.postifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1uf7PZj0PC_hrLUsILPBaxNNrJUJmEfI',
    appId: '1:388128570387:ios:0142a8de056715e31353e6',
    messagingSenderId: '388128570387',
    projectId: 'postify-app-project',
    storageBucket: 'postify-app-project.firebasestorage.app',
    iosBundleId: 'com.example.postifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Ukw_Z4ZiLpk4lT73PsZ6lQAz788HnWw',
    appId: '1:388128570387:web:c36097b7016222981353e6',
    messagingSenderId: '388128570387',
    projectId: 'postify-app-project',
    authDomain: 'postify-app-project.firebaseapp.com',
    storageBucket: 'postify-app-project.firebasestorage.app',
  );
}
